module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'vision',
      label: 'Introduction and Vision',
    },
    {
      type: 'doc',
      id: 'enterprise_vision_solution',
      label: 'Enterprise Vision & Solution',
    },
    {
      type: 'doc',
      id: 'overview',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'Core_Concepts',
      label: 'Core Concepts',
    },
    {
      type: 'doc',
      id: 'quick_start',
      label: 'Quick Start',
    },
    {
      type: 'doc',
      id: 'prerequisites',
      label: 'Prerequisites',
    },
    {
      type: 'doc',
      id: 'architecture',
      label: 'Architecture',
    },
    {
      type: 'doc',
      id: 'adoption',
      label: 'Adoption and Customization',
    },
    {
      type: 'doc',
      id: 'operational_guide',
      label: 'Operational Guide',
    },
    {
      type: 'doc',
      id: 'stack_agent',
      label: 'Validation API',
    },
    {
      type: 'doc',
      id: 'migration',
      label: 'Migration',
    },
    {
      type: 'doc',
      id: 'migration_vm_example',
      label: 'Example: VM to Kubernetes',
    },
    {
      type: 'doc',
      id: 'self-service',
      label: 'Self-service',
    },
    {
      type: 'doc',
      id: 'security',
      label: 'Security',
    },
    {
      type: 'doc',
      id: 'services',
      label: 'Services',
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: true,
      items: [
        { type: 'doc', id: 'components/airflow', label: 'Airflow' },
        { type: 'doc', id: 'components/alloy', label: 'Alloy' },
        { type: 'doc', id: 'components/apisix', label: 'APISIX' },
        { type: 'doc', id: 'components/cert_manager', label: 'Cert Manager' },
        { type: 'doc', id: 'components/clickhouse', label: 'ClickHouse' },
        { type: 'doc', id: 'components/cnpg', label: 'CloudNativePG' },
        { type: 'doc', id: 'components/external_source_code', label: 'External Source Code' },
        { type: 'doc', id: 'components/fastapi', label: 'FastAPI' },
        { type: 'doc', id: 'components/grafana', label: 'Grafana' },
        { type: 'doc', id: 'components/image_base', label: 'Image Base' },
        { type: 'doc', id: 'components/k6', label: 'K6' },
        { type: 'doc', id: 'components/kafka', label: 'Kafka' },
        { type: 'doc', id: 'components/keda', label: 'KEDA' },
        { type: 'doc', id: 'components/keycloak_operator', label: 'Keycloak Operator' },
        { type: 'doc', id: 'components/langflow', label: 'LangFlow' },
        { type: 'doc', id: 'components/loki', label: 'Loki' },
        { type: 'doc', id: 'components/minio', label: 'MinIO' },
        { type: 'doc', id: 'components/mongodb', label: 'MongoDB' },
        { type: 'doc', id: 'components/opa', label: 'OPA' },
        { type: 'doc', id: 'components/open-webui', label: 'Open WebUI' },
        { type: 'doc', id: 'components/otel', label: 'OpenTelemetry' },
        { type: 'doc', id: 'components/prometheus', label: 'Prometheus' },
        { type: 'doc', id: 'components/qdrant', label: 'Qdrant' },
        { type: 'doc', id: 'components/rabbitmq', label: 'RabbitMQ' },
        { type: 'doc', id: 'components/seaweedfs', label: 'SeaweedFS' },
        { type: 'doc', id: 'components/valkey', label: 'Valkey' },
        { type: 'doc', id: 'components/velero', label: 'Velero' },
        { type: 'doc', id: 'components/vllm', label: 'vLLM' },
      ],
    },
    {
      type: 'doc',
      id: 'stack_liveview',
      label: 'Stack LiveView',
    },
    {
      type: 'doc',
      id: 'common_use_cases',
      label: 'Common Use Cases',
    },
    {
      type: 'doc',
      id: 'private_saas_deployment',
      label: 'Private SaaS Deployment',
    },
    {
      type: 'doc',
      id: 'organizational_control',
      label: 'Organizational Control',
    },
    {
      type: 'doc',
      id: 'sovereignty',
      label: 'Sovereignty & Agnostic Freedom',
    },
    {
      type: 'doc',
      id: 'qna',
      label: 'Q&A',
    },
    {
      type: 'doc',
      id: 'multi_stack_observability',
      label: 'Multi-Stack Observability',
    },
    {
      type: 'doc',
      id: 'ai_ops',
      label: 'AI Ops',
    },
    {
      type: 'doc',
      id: 'ai_governance',
      label: 'AI Governance & MCP',
    },
  ],
};
