// src/components/tasks.js
const initialTasks = [
    {
      id: 1,
      team: 'Architects',
      phase: 'day0',
      process: 'Design',
      description: 'Design topology, flows versioning strategies, API definitions, libraries...',
      numberOfServices: 6,
      numberOfHours: 5,
      salaryPerHour: 60,
      staticSupport: 80,
      total: 1800,
      totalCostAfterStatic: 0,
    },
    {
      id: 2,
      team: 'Architects',
      phase: 'day0',
      process: 'Test',
      description: 'POC the foundational structure & core functionalities like API ...',
      numberOfServices: 10,
      numberOfHours: 5,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 3000,
      totalCostAfterStatic: 0,
    },
    {
      id: 3,
      team: 'Architects',
      phase: 'day0',
      process: 'Security Planning',
      description: 'Identifying potential security threats & planning mitigation strategies...',
      numberOfServices: 8,
      numberOfHours: 2,
      salaryPerHour: 60,
      staticSupport: 95,
      total: 960,
      totalCostAfterStatic: 0,
    },
    {
      id: 4,
      team: 'Architects',
      phase: 'day0',
      process: 'Knowledge & Onboarding',
      description: 'Knowledge-base to the team with: API Design, stack components, Architecture Design, Security, etc..',
      numberOfServices: 10,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 95,
      total: 600,
      totalCostAfterStatic: 0,
    },
    {
      id: 5,
      team: 'Devops',
      phase: 'day1',
      process: 'build /packaging',
      description: 'Encapsulating the app source code within Docker containers to fulfill specific requirements, API interactions, and microservices connectivity.',
      numberOfServices: 4,
      numberOfHours: 4,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 960,
      totalCostAfterStatic: 0,
    },
    {
      id: 6,
      team: 'Devops',
      phase: 'day1',
      process: 'Templating Deployment',
      description: 'Crafting HELM charts and Kubernetes YAML files for resources like Ingress, and Deployments..',
      numberOfServices: 10,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 600,
      totalCostAfterStatic: 0,
    },
    {
      id: 7,
      team: 'Devops',
      phase: 'day1',
      process: 'Templating Env',
      description: 'Templating Secrets and ConfigMaps, encrypted for secure variable management...',
      numberOfServices: 4,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 240,
      totalCostAfterStatic: 0,
    },
    {
      id: 8,
      team: 'Devops',
      phase: 'day1',
      process: 'K8s Resource management',
      description: 'Implementing GitOps like Argo, Kustomize for resource management in K8s...',
      numberOfServices: 10,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 95,
      total: 600,
      totalCostAfterStatic: 0,
    },
    {
      id: 9,
      team: 'Devops',
      phase: 'day1',
      process: 'monitoring',
      description: 'Setting up monitoring such as Prometheus/Grafana for service-specific metrics and dashboard configuration...',
      numberOfServices: 8,
      numberOfHours: 2,
      salaryPerHour: 60,
      staticSupport: 95,
      total: 960,
      totalCostAfterStatic: 0,
    },
    {
      id: 10,
      team: 'Devops',
      phase: 'day1',
      process: 'API routing',
      description: 'Creation of API-GW or Ingress controller to manage routing, CORs & access control and SSL issuing',
      numberOfServices: 3,
      numberOfHours: 3,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 540,
      totalCostAfterStatic: 0,
    },
    {
      id: 11,
      team: 'Devops',
      phase: 'day1',
      process: 'Logs aggregation',
      description: 'Implementing centralized log aggregation solutions using stacks such as ELK, Loki, or Minio.',
      numberOfServices: 10,
      numberOfHours: 2,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 1200,
      totalCostAfterStatic: 0,
    },
    {
      id: 12,
      team: 'Devops',
      phase: 'day1',
      process: 'API Definition',
      description: 'Establishing API configurations, dependencies, and definitions to enable service-to-service communication...',
      numberOfServices: 1,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 60,
      totalCostAfterStatic: 0,
    },
    {
      id: 13,
      team: 'SRE',
      phase: 'day1',
      process: 'Auto-Scale',
      description: 'Configuring auto-scaling and system health mechanisms based on specific metrics and conditions.',
      numberOfServices: 5,
      numberOfHours: 3,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 900,
      totalCostAfterStatic: 0,
    },
    {
      id: 14,
      team: 'SRE',
      phase: 'day1',
      process: 'Test & Health',
      description: 'Defining automation for application tests using tools like k6 or JMeter to validate application health.',
      numberOfServices: 5,
      numberOfHours: 4,
      salaryPerHour: 60,
      staticSupport: 85,
      total: 1200,
      totalCostAfterStatic: 0,
    },
    {
      id: 15,
      team: 'DevSecops',
      phase: 'day1',
      process: 'Authorization',
      description: 'Configure NetworkPolicies or Authorization for service2service communication',
      numberOfServices: 8,
      numberOfHours: 2,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 960,
      totalCostAfterStatic: 0,
    },
    {
      id: 16,
      team: 'Devops',
      phase: 'day1',
      process: 'Backup',
      description: 'Establishing automated backup and restore processes for all stateful resources based cron job.',
      numberOfServices: 5,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 300,
      totalCostAfterStatic: 0,
    },
    {
      id: 17,
      team: 'Devops',
      phase: 'day1',
      process: 'CI/CD',
      description: 'Setting up CI/CD pipelines to automate code deployment for each service, including steps like image scanning and testing.',
      numberOfServices: 8,
      numberOfHours: 4,
      salaryPerHour: 60,
      staticSupport: 80,
      total: 1920,
      totalCostAfterStatic: 0,
    },
    {
      id: 18,
      team: 'DevSecOps',
      phase: 'day1',
      process: 'Security Policies',
      description: 'Developing policies using frameworks such as OPA or RBAC to control access and enforce restrictions on resources.',
      numberOfServices: 1,
      numberOfHours: 1,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 60,
      totalCostAfterStatic: 0,
    },
    {
      id: 19,
      team: 'Devops',
      phase: 'day1',
      process: 'Cross-Team Collaboration',
      description: 'inter-team collaboration on shared efforts among DevOps, SecOps, and Development teams across tasks.',
      numberOfServices: 8,
      numberOfHours: 4,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 1920,
      totalCostAfterStatic: 0,
    },
    {
      id: 20,
      team: 'Developers',
      phase: 'day2',
      process: 'Secret Mgmt & SOPs',
      description: 'Implementing SOPs for encrypting sensitive information and managing secrets.',
      numberOfServices: 10,
      numberOfHours: 3,
      salaryPerHour: 60,
      staticSupport: 100,
      total: 1800,
      totalCostAfterStatic: 0,
    },
    {
      id: 21,
      team: 'Devops',
      phase: 'day2',
      process: 'Migration Ready',
      description: 'Create migration mechanism for pro and dev using standard tools like Argo Rollout.',
      numberOfServices: 5,
      numberOfHours: 4,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 1200,
      totalCostAfterStatic: 0,
    },
    {
      id: 22,
      team: 'Devops',
      phase: 'day2',
      process: 'Versioning',
      description: 'Maintaining version upgrades and implementing validation mechanisms for consistent application performance.',
      numberOfServices: 10,
      numberOfHours: 3,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 1800,
      totalCostAfterStatic: 0,
    },
    {
      id: 23,
      team: 'All Teams',
      phase: 'day2',
      process: 'documentations',
      description: 'Ensuring ongoing knowledge sharing and documentation updates for APIs, new versions, and more.',
      numberOfServices: 10,
      numberOfHours: 2,
      salaryPerHour: 60,
      staticSupport: 90,
      total: 600,
      totalCostAfterStatic: 0,
    },
    {
      id: 24,
      team: 'All Teams',
      phase: 'day2',
      process: 'modification',
      description: 'change topology , add services , modify or replace.',
      numberOfServices: 3,
      numberOfHours: 8,
      salaryPerHour: 60,
      staticSupport: 80,
      total: 1440,
      totalCostAfterStatic: 0,
    },
  ];
  
  export default initialTasks;
  